# Task priorities.
LISTEN_PRIOR = 1000
SAY_PRIOR = 1
ACTUATION_PRIOR = 2
POSE_PRIOR = 200
SEARCH_PRIOR = 3
REMEMBER_PRIOR = 3
GO_TO_PRIOR = 4
HEALTH_PRIOR = 100
SHOW_REMINDERS_PRIOR = 100
CHOREGRAPHE_BEHAVIOUR_PRIOR = 100
RECOGNIZE_ACTIVITY_PRIOR = 100

# Maximum length of the dislayed stringify task.
max_display_length = 40